<?php

namespace App\Model\Table;

class CommentsTable extends \Cake\ORM\Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->belongsTo('Users')->setDependent(true);
        $this->addBehavior('Timestamp');
    }
}
