<?php

namespace App\Model\Table;

class PhotosTable extends \Cake\ORM\Table
{

    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->hasMany('Comments')->setDependent(true);
        $this->belongsTo('Users')->setDependent(true);
    }

}
