<?php

namespace App\Model\Table;

class UsersTable extends \Cake\ORM\Table
{
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }
}
